name: Deploy

on:
  push:
    branches: [docker]
  pull_request:
    branches: [docker]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull latest Docker image
      run: |
        docker pull ghcr.io/nakamo312/catty-reminders-app:latest

    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: course.prafdin.ru
        port: 2436
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting Docker deployment..."
          
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          docker stop catty-app || true
          docker rm catty-app || true
          
          docker pull ghcr.io/nakamo312/catty-reminders-app:latest
          
          docker run -d \
            --name catty-app \
            --restart unless-stopped \
            -p 8181:8181 \
            -e ENVIRONMENT=production \
            ghcr.io/nakamo312/catty-reminders-app:latest